language: java
jdk:
  - oraclejdk8
before_install:
  - nvm install 8.9.4
  - cd ./generator-java
  - npm i -g makeshift && makeshift -r https://registry.npmjs.org
  - npm i -g standard-version
install:
  - npm install
  - npm run install_linked_dependencies
before_script:
  - cd /tmp
  - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
  - unzip -qq gradle-3.5-bin.zip
  - export GRADLE_HOME=/tmp/gradle-3.5
  - wget https://github.com/github/hub/releases/download/v2.5.1/hub-linux-386-2.5.1.tgz
  - tar -xvzf hub-linux-386-2.5.1.tgz
  - mv hub-linux-386-2.5.1 hub
  - wget https://kubernetes-helm.storage.googleapis.com/helm-v2.7.2-linux-amd64.tar.gz
  - tar -xvf helm-v2.7.2-linux-amd64.tar.gz
  - export PATH=$GRADLE_HOME/bin:/tmp/hub/bin:/tmp/linux-amd64:$PATH
  - gradle -v
  - git clone -b master https://github.com/ibm-developer/standard-npm-devops.git
  - cd $TRAVIS_BUILD_DIR/generator-java
script:
  - npm run lint || travis_terminate 1
  - npm test || travis_terminate 1
  - npm run testint || travis_terminate 1
  - npm run coveralls
  - npm run testcommon || travis_terminate 1
  - /tmp/standard-npm-devops/do_devops.sh
branches:
  only:
  - master
  - develop
env:
  - DEV_BRANCH=develop PROD_BRANCH=master DEVOPS_SCRIPT_DIR="/tmp/standard-npm-devops" BEFORE_VERSION_BUMP="cd generator-java && npm run update_linked_dependencies && cd -"