language: java
jdk:
  - oraclejdk8
before_install:
  - nvm install 8.9.4
  - cd ./generator-liberty
  - npm i -g makeshift && makeshift -r https://registry.npmjs.org
  - npm i -g standard-version
install:
  - npm install
before_script:
  - cd /tmp
  - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
  - unzip -qq gradle-3.5-bin.zip
  - export GRADLE_HOME=/tmp/gradle-3.5
  - wget https://github.com/github/hub/releases/download/v2.5.1/hub-linux-386-2.5.1.tgz
  - tar -xvzf hub-linux-386-2.5.1.tgz
  - mv hub-linux-386-2.5.1 hub
  - export PATH=$GRADLE_HOME/bin:/tmp/hub/bin:$PATH
  - gradle -v
  - git clone -b master https://github.com/ibm-developer/standard-npm-devops.git
  - cd $TRAVIS_BUILD_DIR/generator-liberty
script:
  - npm run lint
  - npm test
  - npm run testint
  - npm run coveralls
  - /tmp/standard-npm-devops/do_devops.sh
branches:
  only:
  - master
  - develop
env:
  - DEV_BRANCH=develop PROD_BRANCH=master DEVOPS_SCRIPT_DIR="/tmp/standard-npm-devops"
