container-name-run : "{{appName}}"
container-name-tools : "{{appName}}-tools"

host-path-run : "target"
# host-path-run : "build"
host-src-path : ""
container-src-path : "/project"

container-port-map : "9080:9080,9443:9443"
container-port-map-debug : "7777:7777"

dockerfile-run : "Dockerfile-run"
dockerfile-tools : "Dockerfile-tools"
image-name-run : "{{appName}}"
image-name-tools : "javaclitools"

build-cmd : "cd /project ; mvn install"
# build-cmd : "cd /project ; gradle build"
test-cmd : "cd /project ; mvn install"
# test-cmd : "cd /project ; gradle build"

run-cmd : "server run"
debug-cmd : "server debug"
stop-cmd : "server stop"
